name: CMake

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux GCC 9",
            os: ubuntu-latest,
            generator: Ninja,
            toolset: gcc,
            cc: "gcc-9", cxx: "g++-9",
            cxxflags: "-Wall -Wextra -Werror"
          }
        - {
            name: "Linux Clang 9",
            os: ubuntu-latest,
            generator: Ninja,
            toolset: gcc,
            cc: "clang-9", cxx: "clang++-9",
            cxxflags: "-Wall -Wextra -Werror"
          }
        - {
            name: "macOS Clang",
            os: macos-latest,
            generator: Ninja,
            toolset: gcc,
            cc: "clang", cxx: "clang++",
            cxxflags: "-Wall -Wextra -Werror"
          }
        - {
            name: "Windows MSVC 2019",
            os: windows-latest,
            generator: Visual Studio 16 2019,
            toolset: msvc14.2,
            cc: "cl", cxx: "cl",
            cxxflags: "-W4 -WX -permissive- -Zc:preprocessor -wd5105"
          }
        - {
            name: "Windows MSVC 2019 (permissive)",
            os: windows-latest,
            generator: Visual Studio 16 2019,
            toolset: msvc14.2,
            cc: "cl", cxx: "cl",
            cxxflags: "-W4 -WX"
          }
        build_type: [Release]

    steps:
    - uses: actions/checkout@v1

    - name: Install boost
      uses: MarkusJx/install-boost@v1.0.1
      id: install-boost
      with:
      boost_version: 1.73.0
      toolset: ${{ matrix.config.toolset }}

    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B build
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Configure
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
        CXXFLAGS: ${{ matrix.config.cxxflags }}
      run: |
        cd src
        mkdir build
        cd build
        cmake -G"${{ matrix.config.generator }}" \
            -DCMAKE_CXX_STANDARD=14 \
            -DCMAKE_CXX_EXTENSIONS=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DBUILD_BENCHMARKS=OFF \
            -DBUILD_EXAMPLE=ON \
            -DBUILD_TESTING=ON \
            ..
    - name: Build
      working-directory: build
      run: |
        cmake --build . --config ${{ matrix.build_type }}
