name: CMake

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.config.name }} - ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Linux GCC 9",
            os: ubuntu-latest,
            generator: MinGW Makefiles,
            generator-architecture: Win32,
            toolset: gcc
          }
        - {
            name: "Linux Clang 9",
            os: ubuntu-latest,
            generator: MinGW Makefiles,
            generator-architecture: Win32,
            toolset: gcc
          }
        - {
            name: "macOS Clang",
            os: macos-latest,
            generator: MinGW Makefiles,
            generator-architecture: Win32,
            architecture: 
            toolset: gcc
          }
        - {
            name: "Windows MSVC 2019",
            os: windows-latest,
            generator: Visual Studio 16 2019,
            generator-architecture: Win32,
            toolset: msvc14.2
          }
        - {
            name: "Windows MSVC 2019 (permissive)",
            os: windows-latest,
            generator: Visual Studio 16 2019,
            generator-architecture: Win32,
            toolset: msvc14.2
          }
        build_type: [Release]

    steps:
    - uses: actions/checkout@v1

    - name: Install boost
      uses: MarkusJx/install-boost@v1.0.1
      id: install-boost
      with:
        boost_version: 1.73.0
        toolset: ${{ matrix.config.toolset }}

    - name: Configure
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: |
        mkdir build
        cd build
        cmake ../src \
            -G"${{ matrix.config.generator }}" \
            -A"${{ matrix.config.generator-architecture }}" \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      working-directory: build
      run: |
        cmake --build . --config ${{ matrix.build_type }}
